config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	# statement to associate message to a user
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #asociation of user to his messages
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message
    before_action :find_comment, only:[:edit, :update, :destroy]
    before_action :authenticate_user!
	#creating a method that gives us the ability to create a comment with respect to the current user and message 
	def create
		@message =Message.find(params[:message_id])
		@comment =@message.comments.create(comment_params)
		@comment.user_id =current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end

		
	end
	def edit
		
	end
	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render 'edit'
			
		end
		
	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
		
	end

	private
	  def comment_params
	  	params.require(:comment).permit(:content)
	  	
	  end

	  def find_message
	  	@message = Message.find(params[:message_id])

	  end

	  def find_comment
	  	@comment = @message.comments.find(params[:id])
		
	  	
	  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

   before_action :find_message, only:[:show, :edit, :update, :destroy]
   before_action :authenticate_user!, except:[:index, :show]
	def index
		@messages =Message.all.order("created_at DESC")
		
	end

	def new
		@message =current_user.messages.build		
	end
	def create
		@message =current_user.messages.build(message_params)
		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
		
	end

	def show
		
	end

	def edit
		
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
		
	end

	def destroy
		@message.destroy
		redirect_to root_path
		
	end
	private
	  def message_params
	  	 params.require(:message).permit(:title, :description)

	  end


	def find_message
		@message =Message.find(params[:id])
		
	end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by:<%= comment.user.email %><%= time_ago_in_words(comment.created_at) %> ago.</p>
	<div class="links">
		<% if user_signed_in? %><!--a condition to check if user is loged in before limitin the action-->
		  <% if comment.user_id == current_user.id %><!--a condition to chech if the user requesting a certain actin is the one who created it-->

			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
			<%= button_to "Delete", message_comment_path(comment.message, comment), method: :delete, data:{confirm:"are you sure?"} %>
		  <%end%>
		<%end%>
	</div>
</div>

app/views/comments/_form.html.erb
<!-- a form to build comments with respect to messages -->
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label:"Comment:" %>
  <%= f.button :submit, :class =>'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
 <%= f.input :content, label:"Comment" %>
 <%= f.button :submit, :class =>'btn-custom' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<!--designing the navigation bar to have the sign up log in and sign out links -->
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Message Board", root_path, class: "navbar-brand" %><!--a name to our application to be displayed on the navigation bar-->          
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <!--a condition-->
          <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :get %></li>
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
          
        </ul>
        <% if user_signed_in? %>
        <p><%= link_to "New Message", new_message_path, class: "navbar-right navbar-text navbar-link" %></p>
        <% end %>

        
      </div>
    </div>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, lable:"Message title" %>
  <%= f.input :description %>
  <%= f.button :submit %>


<%end%>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form' %>

app/views/messages/index.html.erb
<!--looping through the message title in a descending order in index view-->
<% @messages.each do |message| %>
	<div class="col-md-4">
		<div class="message">
		    <h2 class="message-title"><%= message.title %></h2>
			<%= link_to "Read Message", message_path(message), class:"btb btn-default" %>
			
		</div>
	</div>

<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>New Messages</h1>
	<%= render 'form' %><!--rendering a new message form-->
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<!--showing message tittle and its description-->
		<h2><%= @message.title %></h2>
		<!--add timestamp and user name-->
		 <p class="message-posted-by">Posted by:<%= @message.user.email %><%= time_ago_in_words(@message.created_at) %> ago.</p>
		<p class="message-desc"><%= @message.description %></p>

		<h3>Comment</h3>
		<%= render @message.comments %><!-- this is where the _comment.html.erb partile file will be rendered -->

		<h3 class="reply-to-msg">Reply on the message:</h3>
		<%= render 'comments/form' %><!-- rendering the comment form prefixet with comments since its not on the same directory with show message -->
		<div class="link btn-group">
			<!--back, delet and edit links-->
			<%= link_to "Back", root_path,  class:"btn btn-default" %>

			<% if user_signed_in? %><!--a condition to check if user is loged in before limitin the action-->
			  <% if @message.user_id == current_user.id %><!--a condition to chech if the user requesting a certain actin is the one who created it-->

				<%= link_to "Edit Message", edit_message_path(@message), class:"btn btn-default" %>
				<%= button_to "Delete Message", message_path(@message), method: :delete, data:{confirm:"are you sure?"},  class:"btn btn-default" %>
			  <%end%>
			<%end%>
		</div>
	</div>
</div>